// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server;

namespace Server.Migrations
{
    [DbContext(typeof(SmartShareContext))]
    [Migration("20190208173621_RecreateWithTimestamp")]
    partial class RecreateWithTimestamp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Server.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("file_id");

                    b.Property<DateTime>("Expiration")
                        .HasColumnName("expiration");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnName("file_name");

                    b.Property<int>("MaxDownload")
                        .HasColumnName("max_download");

                    b.Property<string>("Password")
                        .HasColumnName("password");

                    b.Property<byte[]>("TheFile")
                        .HasColumnName("file");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnName("time_created");

                    b.Property<int>("TotalDownload")
                        .HasColumnName("total_download");

                    b.HasKey("Id");

                    b.HasAlternateKey("FileName")
                        .HasName("AlternateKey_FileName");

                    b.ToTable("filemanager");
                });
#pragma warning restore 612, 618
        }
    }
}
